### ISSUE TITLE
net-misc/yt-dlp ModuleNotFoundError: No module named '_ssl'

### ISSUE THREAD

**Issue by jeandestouches** [gentoo/libressl#457]
After switching from openssl to libressl (3.5.3), net-misc/yt-dlp-2022.10.4 doesn't start.

````
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/yt-dlp", line 5, in <module>
    from yt_dlp import main
  File "/usr/lib/python3.10/site-packages/yt_dlp/__init__.py", line 18, in <module>
    from .cookies import SUPPORTED_BROWSERS, SUPPORTED_KEYRINGS
  File "/usr/lib/python3.10/site-packages/yt_dlp/cookies.py", line 18, in <module>
    from .aes import (
  File "/usr/lib/python3.10/site-packages/yt_dlp/aes.py", line 6, in <module>
    from .utils import bytes_to_intlist, intlist_to_bytes
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 36, in <module>
    import ssl
  File "/usr/lib/python3.10/ssl.py", line 99, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
````
Is a patch needed ? Or is it something else ?
Any help appreciated, thanks.

**Comment by orbea** [comment]
@jeandestouches What python version do you have?

With `net-misc/yt-dlp-2022.10.4::gentoo` and `dev-lang/python-3.10.6_p4::libressl` this works for me.

This is my test link: https://www.youtube.com/watch?v=QPba-i26YNA

I used to be able to reproduce with issue with `python:3.9` from the `::gentoo` repo, but it should be fixed in this overlay.

**Comment by orbea** [comment]
Also maybe try the `gnutls` USE in ffmpeg instead of `openssl`.

**Comment by jeandestouches** [comment]
@orbea
Thanks. It my was my fault, sorry.
I rebuilt again dev-lang/python-3.10.6_p4::libressl and now it works. (I've had the wrong xpak installed previously..)
